"path" "scripts/plugins/mikk/"
"custom_weapon/custom_weapon.as"
"custom_weapon/schema.json"
"custom_weapon/weapon_test.json"
"utils/json.as"
"utils/EntityFuncs.as"
"utils/fft.as"
"utils/PlayerFuncs.as"
"utils/UserMessages.as"
"utils/CustomKeyValues.as"
