"path" "scripts/plugins/mikk/"
"custom_weapon/main.as"
"custom_weapon/Logger.as"
"custom_weapon/Register.as"
"custom_weapon/weapon.as"
"custom_weapon/ammo.as"
"custom_weapon/schema_ammo.json"
"custom_weapon/schema_weapon.json"
"utils/json.as"
"utils/EntityFuncs.as"
"utils/fft.as"
"utils/PlayerFuncs.as"
"utils/UserMessages.as"
"utils/CustomKeyValues.as"
