"path" "scripts/plugins/mikk/BetterWeapons/"
"BetterWeapons/weapon_9mmhandgun.as"
"path" "scripts/plugins/mikk/"
"BetterWeapons/BetterWeapons.as"
"BetterWeapons/BetterWeapons.json"
"utils/json.as"
"utils/Reflection.as"
