name: GoldSrc2Sven Tool
description: Issue or suggestion related to GoldSrc2Sven
title: "[GoldSrc2Sven] "
labels: [ "Tools", "GoldSrc2Sven" ]
assignees: [ "mikk155" ]

body:
  - type: markdown
    attributes:
      value: |
        Describe the issue/suggestion
  - type: textarea
    attributes:
      label: "Describe the issue/suggestion"
