/**
*   MIT License
*
*   Copyright (c) 2025 Mikk155
*
*   Permission is hereby granted, free of charge, to any person obtaining a copy
*   of this software and associated documentation files (the "Software"), to deal
*   in the Software without restriction, including without limitation the rights
*   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*   copies of the Software, and to permit persons to whom the Software is
*   furnished to do so, subject to the following conditions:
*
*   The above copyright notice and this permission notice shall be included in all
*   copies or substantial portions of the Software.
*
*   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*   SOFTWARE.
**/

#if AS_GENERATE_DOCUMENTATION
#include <string>
#include <string_view>
#include <cstdio>
#include <filesystem>
#include <ctime>
#include <chrono>
#include <atomic>
#include <thread>
#include <vector>
#include <mutex>

#include "../utils/File.hpp"
#include "../utils/curl.hpp"

#include <fmt/core.h>

#ifndef EXTERNAL_PROGRAM_TEST
#include "mandatory.h"
#endif

#if WIN32
#include <windows.h>
#endif
#if LINUX
// convertToUTF8
#endif

#pragma once

// Log a single literal string
#define LOG(fmt_str) { \
    std::lock_guard<std::mutex> lock(state->bufferMutex); \
    state->buffer.push_back( "[GenerateASPredefined] " fmt_str "\n" ); }

// Log a formated literal string using fmt::format style
#define LOG_ARGS(fmt_str, ...) { \
    std::lock_guard<std::mutex> lock(state->bufferMutex); \
    state->buffer.push_back( fmt::format( "[GenerateASPredefined] " fmt_str "\n", __VA_ARGS__ ) ); }

namespace GenerateASPredefined
{
static std::string ASPredefinedHeader( std::string time )
{
    return fmt::format( R"(/**
 *  AngelScript predefined file snippets for the metamod plugin "ASLP"
 *
 *  This file has been auto-generated by metamod plugin "ASLP"
 *  AngelScript Extended API Limitless Potential By Gaftherman & Mikk
 *
 *  Generation date: {}
 *
 *  This file contains API generated for both the Game's default API and ASLP extended API that can be found in the "aslp" namespace.
 *
 *  If your metamod plugin does extend the game's API as well you can run GenerateASPredefined on startup and generate your own file
 *  Refeer to: https://github.com/Mikk155/Sven-Co-op/blob/main/src/aslp/misc/GenerateASPredefined.hpp
 */
)", time );
}

struct ThreadState
{
    std::atomic<bool> cancel{false};
    std::atomic<bool> done{false};

    std::mutex bufferMutex;
    std::vector<std::string> buffer;
};

inline void Generate( ThreadState* state )
{
    // Convert from a specific source encoding (e.g., system's active code page CP_ACP) to UTF-8
    auto convertToUTF8 = []( std::string& sourceStr ) -> std::string&
    {
#if WIN32
        int sizeNeededForWstr = MultiByteToWideChar( CP_ACP, 0, sourceStr.c_str(), -1, nullptr, 0 );
        std::wstring wstr( sizeNeededForWstr, 0 );
        MultiByteToWideChar( CP_ACP, 0, sourceStr.c_str(), -1, &wstr[0], sizeNeededForWstr );

        int sizeNeededForUtf8 = WideCharToMultiByte( CP_UTF8, 0, wstr.c_str(), -1, nullptr, 0, nullptr, nullptr );
        std::string utf8Str( sizeNeededForUtf8, 0 );
        WideCharToMultiByte( CP_UTF8, 0, wstr.c_str(), -1, &utf8Str[0], sizeNeededForUtf8, nullptr, nullptr );

        // Remove the null terminators that MultiByteToWideChar/WideCharToMultiByte add
        // when using -1 for the input length
        utf8Str.resize(sizeNeededForUtf8 - 1);
        sourceStr = std::move( utf8Str );
#endif
#if LINUX
        // -TODO Maybe linux?
#endif
        return sourceStr;
    };

    std::string currentTime;
    {
        auto now = std::chrono::system_clock::now();
        std::time_t now_c = std::chrono::system_clock::to_time_t( now );
        std::tm* now_tm = std::localtime( &now_c );

        char time_buffer[11];
        std::strftime( time_buffer, 11, "%Y-%m-%d", now_tm );
        currentTime = string( time_buffer );
    }

    File as_predefined( "svencoop_addon/test/GenerateASPredefined/as.predefined" );
    as_predefined.Base = true;
    as_predefined.Write( ASPredefinedHeader( currentTime ) );
    as_predefined.Append( "\n" );
    // Default AS objects

    if( curl::Initialize() )
    {
        std::string url = "https://codeberg.org/anggaranothing/svencoop-py-asdocs-vscode/raw/branch/dev/default.as.predefined";

        curl::Request req = {
            .url = url
        };

#if 0
        File default_predefined( "svencoop_addon/default.as.predefined" );
        default_predefined.Base = true;
        default_predefined.Engine = false;
#endif

        if( auto code = req.Perform(); code == curl::Response::Ok && req.status == 200 )
        {
#if 0
            default_predefined.Write( req.response );
#endif
            as_predefined.Append( fmt::format( "// Default predefined requested from: {}\n\n", url ) );
            as_predefined.Append( req.response );
            as_predefined.Append( "\n" );
        }
        else
        {
#if 0
            LOG_ARGS( "Error: Could not request to {}", url )

            std::string content;
            if( default_predefined.Read( content ) )
            {
                as_predefined.Append( content );
                as_predefined.Append( "\n" );
            }
            else
            {
                LOG_ARGS( "Error: failed to open cache {}\nSkipping default AngelScript objects...", default_predefined.GetFullPath() )
            }
#else
            LOG_ARGS( "Error: Could not request to {}\nSkipping default AngelScript objects...", url )
#endif
        }

        curl::Shutdown();
    }
    else
    {
        LOG( "Error: Could initialize libcurl. Skipping default AngelScript objects..." )
    }

    // -Read asdocs.txt here- and Append to as_predefined

    // -Read hooks.txt here- and Append to as_predefined

    // Get the last console log file for AS Base classes
    std::string asbaseclasses;
    {
        std::string fileName = fmt::format( "console-{}.log", currentTime );
        File asbaseclass_file( fileName );
        asbaseclass_file.Base = true;

        if( asbaseclass_file.Read( asbaseclasses ) && !asbaseclasses.empty() )
        {
            convertToUTF8( asbaseclasses );
            if( size_t startClass = asbaseclasses.find( "abstract class" ); startClass != std::string::npos )
                asbaseclasses = asbaseclasses.substr( startClass );
            asbaseclasses = asbaseclasses.substr( 0, asbaseclasses.rfind( "}", asbaseclasses.find( "end_scriptbaseclasses" ) ) + 1 );
            as_predefined.Append( asbaseclasses );
            as_predefined.Append( "\n" );
        }
        else
        {
            asbaseclasses.clear();
            LOG_ARGS( "Error: Could not parse the abstract base class file {} Skipping...", fileName )
        }
    }

    state->done = true;
}

inline std::thread g_thread;
inline ThreadState* g_state = nullptr;

inline void Start()
{
    g_state = new ThreadState();
    g_thread = std::thread( Generate, g_state );
}

inline void Shutdown()
{
    if( g_state != nullptr )
    {
        g_state->cancel = true;
        g_state->buffer.clear();
        delete g_state;
        g_state = nullptr;
    }

    if( g_thread.joinable() )
        g_thread.join();
}

#ifndef EXTERNAL_PROGRAM_TEST
// Special thanks to AnggaraNothing for the idea: https://github.com/anggaranothing/sc-py-asdocs-vscode
inline void GameDumpData()
{
    static bool ASDocGenerator = false;

    if( !ASDocGenerator )
    {
        // Dump hooks
        SERVER_COMMAND( const_cast<char*>( "as_dumphooks hooks\n" ) );

        // The server may have condebug enabled so do two runs to make sure it's logged
        for( int log = 0; log < 2; log++ )
        {
            // Toggle condebug
            SERVER_COMMAND( const_cast<char*>( "condebug\n" ) );

            // Prefix on log
            SERVER_COMMAND( const_cast<char*>( "echo start_scriptbaseclasses\n" ) );

            // Output abstract classes
            SERVER_COMMAND( const_cast<char*>( "as_scriptbaseclasses\n" ) );

            char* wait = const_cast<char*>( "wait\n" );

            // Wait 120 frames
            for( int i = 0; i < 120; i++ ) {
                SERVER_COMMAND( wait );
            }

            // Suffix on log
            SERVER_COMMAND( const_cast<char*>( "echo end_scriptbaseclasses\n" ) );
        }

        // Call Start() from ClientCommand hook.
        SERVER_COMMAND( const_cast<char*>( "generate_as_predefined\n" ) );

        SERVER_EXECUTE();

        ASDocGenerator = true;
    }
}

inline void StartFrame()
{
    if( g_state != nullptr && g_state->done )
    {
        for( const std::string& str : g_state->buffer )
        {
            ALERT( at_console, str.c_str() );
        }
        Shutdown();
        return;
    }
}
#endif
} // End GenerateASPredefined
#undef LOG
#undef LOG_ARGS
#endif // End AS_GENERATE_DOCUMENTATION
