"path" "scripts/plugins/mikk/"
"AFKManager/AFKManager.as"
"AFKManager/AFKManager.json"
"utils/fft.as"
"utils/json.as"
"utils/Discord.as"
"utils/Language.as"
"utils/EntityFuncs.as"
"utils/PlayerFuncs.as"
"utils/CustomKeyValues.as"