name: AFKManager

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/AFKManager.yaml'
      - 'resources/AFKManager.json'
      - 'scripts/mikk/*'
      - 'scripts/plugins/mikk/AFKManager.*'

permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  APP_NAME: AFKManager

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Python
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Repack resources
      run: python3 build.py ${{ env.APP_NAME }}

    - name: Create Release
      uses: xresloader/upload-to-github-release@v1.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "assets.zip"
        default_release_body_path: CHANGELOG.md
        overwrite: true
        tags: true
        draft: false
        prerelease: false
        tag_name: ${{ env.APP_NAME }}
        branches: main
        default_release_name: ${{ env.APP_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        target_owner: Mikk155
        target_repo: Sven-Co-op

    - name: Update Changelog
      run: python3 changelog.py ${{ env.APP_NAME }}
