name: Generate Dependencies

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: python3 makefiles.py scripts/plugins/mikk/chatbridge.res

    - name: Archive dependencies
      uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: dependencies
