name: chatbridge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python3 makefiles.py resources/chatbridge.res

    - name: Archive dependencies
      uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: dependencies
        if-no-files-found: error
