name: chatbridge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: bash makefiles.bash scripts/plugins/mikk/chatbridge.res
