name: CustomPrecache

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/CustomPrecache.yml'
      - 'src/utils/*'
      - 'src/CustomPrecache/*'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Installing Python
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Release
      env:
        TOKEN: ${{ secrets.TOKEN }}
        BOT: ${{ secrets.BOT }}
      run: python3 build.py CustomPrecache true true
