name: no_autopickup

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/no_autopickup.yml'
      - 'src/utils/*'
      - 'src/no_autopickup.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Installing Python
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Release
      env:
        TOKEN: ${{ secrets.TOKEN }}
        BOT: ${{ secrets.BOT }}
      run: python3 build.py no_autopickup true true
